### ISSUE TITLE
Templates not shown in Casper CG

### ISSUE THREAD

**Issue by Dandrum** [nxtedition/create-caspar-graphics#17]
Hi,

i tested the build example template and a simple just h1-tag Template in Caspar as Template itself and with HTML Page none is shown in casparcg.
But if I remove all JS from React and just display plain html with h1-tag text it works. I think the JS is not executed right in caspar html producer. In my browser everything is fine.

I use Caspar server 2.0.7 e9fc25a Stable

Do i need a Higher Server version because the 2.0.7 uses a  to old chromium ?

UPDATE:
i testet a simple html file:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>test</title>
</head>
<body>
<h1 style="color:#fff">HALLO</h1>
</body>
</html>
<script>
  function play(){
    var element = document.getElementsByTagName("h1")
    element.innerHtml('PLAY');
  }
  function stop(){
    var element = document.getElementsByTagName("h1")
    element.innerHtml('STOP');
  }
  function next(){
    var element = document.getElementsByTagName("h1")
    element.innerHtml('NEXT');
  }
  function update(){
    var element = document.getElementsByTagName("h1")
    element.innerHtml('UPDATE');
  }
</script>
```

A newer server version 2.2.x works but is there no play/pause or next command ?

Greetings 
Dan

**Comment by tobiasandersen** [comment]
Hi @Dandrum, this package is for building Caspar templates in React. I might be missing something, but your question seems to be more about Caspar in general, so this might be a better place to ask your questions: https://github.com/CasparCG/help.

If not, feel free to re-open!
