### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by martingronlund** [nxtedition/create-caspar-graphics#2]
I would love

- a table of contents
- having the `.html`-path quirk under a heading, e.g. "Live debugging with a Caspar"

**Comment by malmgrenola** [comment]
> a table of contents

TOC Here? https://github.com/nxtedition/create-caspar-graphics/blob/master/README.md

> having the .html-path quirk under a heading, e.g. "Live debugging with a Caspar"

Please elaborate, If you refer to any docs in this repo, we would love a PR! :-)

**Comment by martingronlund** [comment]
Ah, fine. I'll do it myself then. But later :)
