### ISSUE TITLE
Graphics preview in background

### ISSUE THREAD

**Issue by 5opr4ni** [nxtedition/create-caspar-graphics#23]
Hi

Is there anyway I can have a sample image in the background when building my template?

/olle

**Comment by tobiasandersen** [comment]
Hi Olle :) 

Yes. You can put an image called `reference.jpg` in the same folder as the template (next to the `index.js` file). And then use `f9` to toggle its visibility.

**Comment by 7u5a** [comment]
> Hi Olle :)
> 
> Yes. You can put an image called `reference.jpg` in the same folder as the template (next to the `index.js` file). And then use `f9` to toggle its visibility.

Does this still work?
