### ISSUE TITLE
Responsive Templates

### ISSUE THREAD

**Issue by tobiasandersen** [nxtedition/create-caspar-graphics#29]
Currently it's a bit hard developing responsive templates inside the preview (because we scale them using transforms to fit inside the preview). We should probably wrap them in iframes instead.

**Comment by 7u5a** [comment]
Is it possible to make responsive  templates, and if, how does anybody do that?

I now made a template, working nice on 1920x1080 but unfortunately, I need to run it in PAL...

**Comment by tobiasandersen** [comment]
It's possible in the latest version. Here's some documentation and a simple example:

https://gfx.nxtedition.com/docs/responsive
https://github.com/nxtedition/create-caspar-graphics/tree/master/packages/examples/templates/responsive-width
