### ISSUE TITLE
Update button not working

### ISSUE THREAD

**Issue by brucedk** [nxtedition/create-caspar-graphics#43]
So, i'm making some graphics here, and now I will have some update features, but when I try to test, the update button wasn't making anything... 

Is it not enable yet?

![Capture](https://user-images.githubusercontent.com/40279859/86623926-cc323c80-bf98-11ea-8673-5872662ffe1f.JPG)

**Comment by tobiasandersen** [comment]
You're right, seems like only the keyboard shortcut works.

**Comment by tobiasandersen** [comment]
This should be fixed in the latest version ([caspar-graphics@1.0.0-beta.27](https://www.npmjs.com/package/@nxtedition/caspar-graphics/v/1.0.0-beta.27)).
