### ISSUE TITLE
Error when call stop() on v2

### ISSUE THREAD

**Issue by brucedk** [nxtedition/create-caspar-graphics#58]
Hello, I was making some tests to use v2, and using the example that comes with it when a stop function it gives me the error of the pic below

![image](https://user-images.githubusercontent.com/40279859/117665133-e6b8e180-b178-11eb-883c-ba5cb9ef75da.png)

**Comment by tobiasandersen** [comment]
How are you using it? If you can show an example I can take a look.

**Comment by brucedk** [comment]
@tobiasandersen I use it via chrome console, I'm using the .html render version, all the other commands works (play, pause, update)
The stop command work, but when it calls onComplete, it gives this error above

**Comment by tobiasandersen** [comment]
https://github.com/nxtedition/create-caspar-graphics/commit/cb282fbabb5ad5020c6f3a57d27dedbeac6ed2be should have fixed that issue — can you try with the latest version (`1.0.0-next.5`)?

**Comment by brucedk** [comment]
I made a `yarn upgrade` here, but now there is another module with this problem:
```
Error: Cannot find module 'C:\Users\Switcher\Documents\GIt\casparhooksriot\node_modules\is-core-module\index.js'
node_modules/caspar-graphics/src/template/create.dev.js
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
```
any thought?

**Comment by brucedk** [comment]
I figure out here, my `yarn` was with some issues, I reinstalled all the packages and now works, thanks
