### ISSUE TITLE
Selectable list of presets in create-caspar-graphics

### ISSUE THREAD

**Issue by tobiasandersen** [nxtedition/create-caspar-graphics#6]
@r01010010 commented on [Fri Jan 04 2019](https://github.com/nxtedition/nxt/issues/2699)

**Is your feature request related to a problem? Please describe.**
In `create-caspar-graphics`: If you want to try different behaviours of a graphic component you have to edit the json and then click on update button, it's kind of frustrating and time consuming. Also is difficult to test all possibilities and probably is almost impossible to make a full coverage when human testing.

**Describe the solution you'd like**
It would be nice if you could load a list of presets instead of having to edit the json every time.
Ideally you could have many presets, included intended error prone ones, and render them all at once and human check them one after the other. That would be neat!

**Describe alternatives you've considered**
- The data tab could be a selectable with the pressets.
- Or there could be clickable tabs with presets names.

![image](https://user-images.githubusercontent.com/698953/50691036-cc621c80-102f-11e9-98d7-e7b9bc313704.png)

---

@ronag commented on [Fri Jan 04 2019](https://github.com/nxtedition/nxt/issues/2699#issuecomment-451450782)

creating and saving tabs would be nice

---

@malmgrenola commented on [Mon Jan 07 2019](https://github.com/nxtedition/nxt/issues/2699#issuecomment-451950234)

@tobiasandersen Isn't this a part of the intelligent templates sending data back to nxt with UI information?

---

@tobiasandersen commented on [Mon Jan 07 2019](https://github.com/nxtedition/nxt/issues/2699#issuecomment-451952293)

I don't think it's the same, but we should probably do it at the same time. This is more for having presets of data to test with. When you develop it's really helpful to have multiple sets of data to test with, and now it's a bit cumbersome to do.

**Comment by r01010010** [comment]
This is done. Commit related https://github.com/nxtedition/create-caspar-graphics/commit/2920c134249690b48f1f640feb7783f37323e87f
