### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by poppaul95** [nxtedition/create-caspar-graphics#62]
Hello, I am getting this error when I try to run the example in preview, does anyone have any idea why?
![image](https://user-images.githubusercontent.com/30286788/126636462-e011690d-b39e-4ba3-ac71-590f6e649d92.png)

**Comment by vimlesh1975** [comment]
Yes I am alo getting this.

**Comment by tobiasandersen** [comment]
Which version are you using? Could you point me to a reproducible example?

**Comment by valurhrafn** [comment]
Just got the same error, steps i did:
* yarn create caspar-graphics caspar-graphics
* cd caspar-graphics
* yarn start

The version of caspar-graphics that got automatically installed is: 
"caspar-graphics": "^1.0.0-next.5"

System: MacOs Big Sur
Node Version: 14.17.5
Yarn version: 1.22.11

**Comment by valurhrafn** [comment]
One observation, If I clone this project and use the create-caspar-graphics from the `v2 branch` locally
preview is working - but it does not work in the version I get from `yarn create` or `npx`

**Comment by tobiasandersen** [comment]
It should now be fixed in the latest version (`1.0.0-next.7`)

**Comment by vimlesh1975** [comment]
> It should now be fixed in the latest version (`1.0.0-next.7`)

Yes, working now.

**Comment by valurhrafn** [comment]
Yes, can also confirm that it is working now - great, thanks!

**Comment by tobiasandersen** [comment]
Thanks for confirming, and thanks for the steps to reproduce @valurhrafn!
