### ISSUE TITLE
Using with Hooks instead of Classes

### ISSUE THREAD

**Issue by brucedk** [nxtedition/create-caspar-graphics#70]
sorry if I'm asking anything stupid, but can we use Hooks api to create the graphics? I'm trying to do that, but it seems that the props from update function aren't coming

**Comment by tobiasandersen** [comment]
Which version of `caspar-graphics` are you running? If you use the v2 branch (they're published on npm with the `next` tag) you can use hooks.

**Comment by brucedk** [comment]
I'm using v2 branch (`1.0.0-next.9.2`), but when I try to call the props, it aways return `undefined` to me

**Comment by tobiasandersen** [comment]
Could you share an example where it's not working?

**Comment by brucedk** [comment]
@tobiasandersen sorry to not give more info, I just see the examples that you put inside this project and notice the mistakes that I had made. 
Thanks again
