### ISSUE TITLE
MIME type issue when playing built template in Caspar client

### ISSUE THREAD

**Issue by TheBerndt** [nxtedition/create-caspar-graphics#84]
Hi,
when playing a working template on a server I get the following error in Caspar frontend log:
`Failed to load module script: the server responded with a non-Javascript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

If I add .js to the end of the module src name I can get rid of this error but I still get "update is not defined" and "play is not defined".

**Comment by tobiasandersen** [comment]
Hi, 

In the newer version released you need to serve the templates from an HTTP Server (e.g. https://www.npmjs.com/package/http-server). If this doesn't work you can use the older package https://www.npmjs.com/package/caspar-graphics instead of https://www.npmjs.com/package/@nxtedition/caspar-graphics. 

Hope that helps.

**Comment by tobiasandersen** [comment]
I haven't tested it on windows, so there could potentially be issues. If you can link to a public repo that has this issue I can take a look. 

I'm also hoping to finalize the new versions and provide some better documentation.

**Comment by TheBerndt** [comment]
I don't have a public repo but basically "npx install caspar-cgraphics graphics -> npm install -> npm run dev" gives this on windows and chrome.

Also noticed that doing the same on a macOS and then trying to play example templates on the caspar client (2.0) and server (2.3.3) does not work. The dev environment works nicely on macOS.  If you happen to have time to update documentation would be nice addition to know the Caspar server versions etc. that are verified working.

But nice work, I had a blast creating templates with react and framermotion. if I just now could figure how to play those on the client/server 😅

**Comment by tobiasandersen** [comment]
If you serve the templates from an https server they should work on server 2.3.3, at least from macOS (that's what we're doing currently).

**Comment by TheBerndt** [comment]
Thanks for helping out @tobiasandersen . I managed to do what you suggested and can play other html templates I've made from the local http server in caspar. In those templates I'm using webcg and have defined play and update as functions. 
When I try to play my own and other example caspar-graphics react templates I still get play & update not defined. 
I'm basically using `const isVisible = state === States.playing` and then calling that in onAnimationComplete `if (!play) {
          safeToRemove()
        }`
        
I have a feeling that I'm defining these caspar command states that are imported from graphics-kit maybe incorrectly?

**Comment by tobiasandersen** [comment]
I don't see anything wrong with what you described above. But If you could somehow share your code I can take a look.

**Comment by TheBerndt** [comment]
Sure, this is the index.js based on the framer motion example file that I started to expand. It's a bit of a mess but works in the dev environment but throws play not defined and update not defined when trying to play it in caspar server NRK version and 2.3.3.  I'm using the built version from dist and serving it from a local http server.

`import React from 'react'
import { render, FramerMotion, useCasparData, useCaspar, States } from '@nxtedition/graphics-kit'
import { motion, isValidMotionProp } from 'framer-motion'
import {
  chakra,
  shouldForwardProp,
  Center,
  Heading,
  Text,
  Stack,
  Icon,
  extendTheme,
  ChakraProvider,
} from '@chakra-ui/react'

//override Chakra default theming - no bg, work sans as fonts
const theme = extendTheme({
  styles: {
    global: () => ({
      body: {
        bg: "",
        //bgImage: "url(./reference.jpg)"
      }
    })
  },
  fonts: {
    heading: `'Work Sans', sans-serif`,
    body: `'Work Sans', sans-serif`,
  },
});

//element used for motion
const ChakraBox = chakra(motion.div, {
  /**
   * Allow motion props and non-Chakra props to be forwarded.
   */
  shouldForwardProp: (prop) => isValidMotionProp(prop) || shouldForwardProp(prop),
});

//Create component for text graphics two rows
const Tg = () => {

  const { name, title, variant } = useCasparData()

  const { state, safeToRemove } = useCaspar()

  const isVisible = state === States.playing


  //hacky color variant support
  let colorVariant = ''
  if (variant == "1") {
    colorVariant = ['#E9F2F9', '#405C8A', '#002663']
  }
  else if (variant == "2") {
    colorVariant = ['#002663', '#C0C9D8', '#FFFFFF']
  }
  else {
    colorVariant = ['#E9F2F9', '#405C8A', '#002663']
  }

  // Create svg as icon
  const Cog = (props) => (
    <Icon viewBox='0 0 64 64' {...props}>
      <path fill={colorVariant[1]} fillRule="evenodd" d="M36.522 0A32.313 32.313 0 0 1 64 27.473H45.646a14.354 14.354 0 0 0-3.478-5.638 14.372 14.372 0 0 0-5.646-3.482V0Zm-9.055 18.362V.005A32.313 32.313 0 0 0 .01 27.473h18.354a14.374 14.374 0 0 1 9.105-9.11Zm0 27.282a14.38 14.38 0 0 1-8.75-8.141c-.133-.321-.254-.646-.363-.975H0A32.318 32.318 0 0 0 27.467 64V45.644Zm18.17-9.116a14.398 14.398 0 0 1-3.477 5.636 14.373 14.373 0 0 1-5.638 3.48v18.354a32.312 32.312 0 0 0 27.47-27.47H45.638Z" clipRule="evenodd"
      />
    </Icon>
  )

  return (
    <ChakraProvider theme={theme}>
      <FramerMotion hide={!name}>
        {/* bg anims */}
        <ChakraBox
          key={name}
          initial={{
            opacity: 0,
            x: 0,
            y: 1100,
            originX: "92px",
            originY: "-196px",
            scaleY: 0
          }}
          animate={{
            opacity: !isVisible ? 0 : 1,
            x: 0,
            y: 1100,
            originX: "92px",
            originY: "-196px",
            scaleY: 1
          }}
          exit={{
            opacity: 0,
            x: 0,
            y: 1100,
            originX: "92px",
            scaleY: 1
          }}
          transition={{
            duration: 0.3,
            ease: "easeInOut",
          }}
          onAnimationComplete={() => {
            if (!isVisible) {
              safeToRemove()
            }
          }}
        >
          <Stack
            pt={4}
            pb={4}
            pl={6}
            // pr={64}
            borderRadius={'sm'}
            pos="absolute"
            bottom={24} left={24}
            color='#002663'
            //bg='#E9F2F9'
            bg={colorVariant[0]}
            direction={'row'}
          >
            <Center>
              {/* cog icon anims */}
              <ChakraBox
                mr={6}
                initial={{
                  opacity: 0,
                  rotate: -90,
                }}
                animate={{
                  opacity: 1,
                  rotate: 0,
                }}
                exit={{
                }}
                transition={{
                  duration: 0.6,
                  delay: 0.3,
                  ease: "easeInOut",
                }}
              >
                <Cog
                  boxSize={16} >
                </Cog>
              </ChakraBox>
              <Stack direction={'column'}>
                {/* text anims */}
                <ChakraBox
                  mr={32}
                  initial={{
                    opacity: 0,
                  }}
                  animate={{
                    opacity: [0, 1],
                  }}
                  exit={{
                    opacity: 0,
                  }}
                  transition={{
                    duration: 0.6,
                    delay: 0.6,
                    ease: "easeInOut",
                  }}>

                  <Text color={colorVariant[1]} fontWeight={700} textTransform="uppercase" letterSpacing='1.5px' fontSize='2xl'>{title}</Text>
                  <Heading color={colorVariant[2]} fontWeight={600} fontSize='3xl'>{name}</Heading>

                </ChakraBox>
              </Stack>
            </Center>
          </Stack>
        </ChakraBox>
      </FramerMotion>
    </ChakraProvider>
  )
}

render(Tg)
`

**Comment by tobiasandersen** [comment]
Do you have the same issue if you open the built version in Chrome and try to call `play()`?

**Comment by TheBerndt** [comment]
Just verified, yes. It’s the same ”play is not defined” in Chrome console also.

**Comment by tobiasandersen** [comment]
Hm, I'm not having any issues with the graphic you posted above after building. Do you get any other errors?

**Comment by TheBerndt** [comment]
Ok that is Interesting. I'm using
`"@nxtedition/graphics-kit": "^2.0.0-alpha.5"
"@nxtedition/caspar-graphics": "^1.0.0-alpha.14"`

**Comment by tobiasandersen** [comment]
Can you try updating to the latest versions and see if that helps first?

**Comment by TheBerndt** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/57284129/217258993-906dc172-4649-486b-9302-1f2c36fdbb3e.png">
I updated to the latest packages with NPM but still. This error is from a locally hosted file :/

**Comment by tobiasandersen** [comment]
That doesn't look like an error though?

**Comment by TheBerndt** [comment]
True, before updating it was a reference error. Now it's just undefined (also on windows & chrome). Thanks for pointing it out, seems my JS skills are lacking a bit here. I'll try to investigate more on this.

**Comment by tobiasandersen** [comment]
Are you sure it's not working as it should now? The `Tg.play()` log suggests it's received the `play` command successfully. If it's not showing in the browser, it could also be that the graphic is located off-screen (in case your screen resolution is less than the graphic's) or that it's waiting for data before showing.

**Comment by TheBerndt** [comment]
I tried it on casparcg and it CG ADDs it but after that caspar throws typeError: object.fromEntries is not a function, referenceError: update is not defined, play is not defined.

I can get rid of the object.fromEntries if i change the type="script" instead of "module" in the index.html but others remain.
In the chrome console it also doesn't throw the referenceError anymore like you pointed out so that's progress 🙂 👍

**Comment by tobiasandersen** [comment]
Okay that makes sense. We target Chrome 71 when building, and `Object.fromEntries()` is not available until v73. So my guess is that one of your other dependencies is using it, but is built for more modern targets (just like you're saying).

**Comment by TheBerndt** [comment]
Yes, adding a polyfill to handle the Object.fromEntries solved this issue and it now plays in the casparcg. Thanks for helping to narrow down the root cause with this template!

**Comment by tobiasandersen** [comment]
Great to hear! So XML didn't work?

**Comment by TheBerndt** [comment]
Yea, XML didn't work for some reason.

**Comment by tobiasandersen** [comment]
I haven't tested that so I've probably made a mistake somewhere. I'll go ahead and close this issue, but feel free to open a new one about the XML issues.
