### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#85]
maybee I'm a newbee.
But if I can't use npm start, why?
Wich software do I need to install on my windows computer to do this?

**Comment by TheBerndt** [comment]
You need to install node.js. NPM is a packacke manager that’s included in node.

**Comment by 7u5a** [comment]
I’ve installed visual studio code and node.js
But does’nt work for me.
Is there a guide anyware?

**Comment by malmgrenola** [comment]
It sound like you are on the right track with your development environment.

There are differences between between operating systems (Windows/Mac OS/Linux) in regards to installation and some tools required.

In the article [how to install nodejs](https://nodejs.dev/en/learn/how-to-install-nodejs/) you can probably get a good start installing node.

I also noticed that the getting started in the [README](https://github.com/nxtedition/create-caspar-graphics#readme) has a couple missing steps and scripts used that have changed. I can create a PR to correct that.

meanwhile, my own getting started looks like this:

## Start using Github

1. Here's where you can find step-by-step guides on the [basics of working with Github](https://guides.github.com/activities/hello-world/).
1. Create your [Github Login](https://github.com/join), if you don't have that already.

## Install Git

1. Open a terminal or `PowerShell` on _windows_.
2. Check your Git version by executing: `git --version`.
3. If Git is not installed, you should be prompted to install it. Follow this [guide](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) to installing Git and linking your account to Git.
4. [setup your username on your computer](https://docs.github.com/en/github/getting-started-with-github/setting-your-username-in-git#setting-your-git-username-for-every-repository-on-your-computer)
5. [Setup you git email addres](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)

On _windows_ you will get a `Git Bash` software that acts as a terminal for future use. You can also use power shell.
Close and open any terminal window to reload the new installations.

## 4. Install NodeJS

[NodeJS](https://nodejs.org/en/) Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.

it will also install `npm` and other packages if you select it

1. In the terminal execute `node --version` to confirm if node is installed, you should see a version.
2. [Install Nodejs](https://nodejs.org/en/) if it's not installed.
3. In the terminal execute `npm --version` to confirm if nvm is installed, you should see a version.


## Fork and Clone the project

As stated in the [Github Docs](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)

> A fork is a copy of a repository. Forking a repository allows you to freely experiment with changes without affecting the original project.
> Most commonly, forks are used to either propose changes to someone else's project or to use someone else's project as a starting point for your own idea.

This means that you can have your very own copy of the site and do whatever you want while editing the content or function of the site.
This is how you create your own fork:

1. Goto to the [create-caspar-graphics](https://github.com/nxtedition/create-caspar-graphics) Repo on GitHub
2. Press the `Fork` button on the top right corner.
4. Open up the green `Code` button and copy the `HTTPS` url.
5. In the terminal navigate to a good root place for the local copy of the website and Clone by executing: `git clone paste-the-https-copy-here` it should be something like `https://github.com/malmgrenola/create-caspar-graphics.git` but with your GitHub username in the middle.

## create caspar graphics

1. In the terminal run `cd create-caspar-graphics` to change to the `create-caspar-graphics` directory.
1. In the terminal run `npm init caspar-graphics my-graphics` to start a new graphics project called `my-graphics`, answer the questions in the script.
1. In the terminal run `cd my-graphics` to go into my-graphics folder
1. In the terminal run `npm install` to install all dependencies.
1. In the terminal run `npm run dev`  to start the graphics project preview and live reload on file changes
1. your default browser opens with url `http://localhost:8080/` and display a graphics example.

If you can see the site you are up running locally! Great job!

**Comment by 7u5a** [comment]
So now something seems to work here...
When I use the npm run dev I get this:

![billede](https://user-images.githubusercontent.com/89579091/219540500-0dfe01de-b09c-43e2-b444-4730422d2408.png)

**Comment by tobiasandersen** [comment]
These docs are a bit outdated unfortunately. I'm working on new documentation here: https://github.com/tobiasandersen/create-caspar-graphics/tree/docs/packages/www/pages/docs. It's not finished yet, but it will hopefully be helpful anyway.

**Comment by 7u5a** [comment]
I just get this no matter what:
![billede](https://user-images.githubusercontent.com/89579091/220078315-43b84a0b-84d9-4c2d-9b44-a878e43592b3.png)
What do I do wrong?

**Comment by 5opr4ni** [comment]
> These docs are a bit outdated unfortunately. I'm working on new documentation here: https://github.com/tobiasandersen/create-caspar-graphics/tree/docs/packages/www/pages/docs. It's not finished yet, but it will hopefully be helpful anyway.

Followed your emerging documentation ❤️
Nice work!!

But I can't get it to run on my CasparCG

This is what I get in the Log
```
[2023-02-27 08:04:31.439] [info]    Received message from 10.152.43.30: CG 1-20 ADD 1 "TESTERNXT/EXAMPLE/INDEX" 1 "<templateData><componentData id=\"f0\"><data id=\"text\" value=\"OLLE\"/></componentData></templateData>"\r\n
[2023-02-27 08:04:31.439] [info]    Sent message to 10.152.43.30:202 CG OK\r\n
[2023-02-27 08:04:31.442] [info]    html[file://c:\\caspar\\SCREENTEXT/SCREENTEXT.html] Destroyed.
[2023-02-27 08:04:31.455] [error]   html[file://c:\\caspar\\TESTERNXT/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
[2023-02-27 08:04:31.456] [error]   html[file://c:\\caspar\\TESTERNXT/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Uncaught ReferenceError: update is not defined
[2023-02-27 08:04:31.456] [error]   html[file://c:\\caspar\\TESTERNXT/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Uncaught ReferenceError: play is not defined
```

**Comment by 7u5a** [comment]
@5opr4ni wich document, did you follow?

**Comment by TheBerndt** [comment]
Hi, I got the same MIME type error when I wasn’t serving templates over http server. Hope this helps.

**Comment by 5opr4ni** [comment]
> @5opr4ni wich document, did you follow?

https://github.com/tobiasandersen/create-caspar-graphics/tree/docs/packages/www/pages/docs/create-your-first-graphic

> Hi, I got the same MIME type error when I wasn’t serving templates over http server. Hope this helps.

That's OK, but in the most use cases in the open-source community, the HTML templates are placed in the template folder on CasparCG not from a web server. 
I know that it's a beautiful solution to serve them from a web server, but in my case, my templates load too slow when doing that and can't be used in many cases. We often have a lot of video assets for both fill and masking in a lot of our templates, and they need to load instantly on request, else the director will kill me. ;)

/Olle

**Comment by tobiasandersen** [comment]
That's actually fixed in that branch, so you'll get everything baked into a single html file. I just haven't released it yet, but will hopefully have some more time to work on it soon.

**Comment by GenerRR** [comment]
> I just get this no matter what: ![billede](https://user-images.githubusercontent.com/89579091/220078315-43b84a0b-84d9-4c2d-9b44-a878e43592b3.png) What do I do wrong?
Hi, did you find a solution to this ?
I have the same problem, the server started, but the graphics are not displayed in the browser (tried different browsers, localhost:8080 and localhost:8080/example, with folder template name ) should be something very simple

**Comment by GenerRR** [comment]
> I just get this no matter what: ![billede](https://user-images.githubusercontent.com/89579091/220078315-43b84a0b-84d9-4c2d-9b44-a878e43592b3.png) What do I do wrong?

Hi, did you find a solution to this ?
I have the same problem, the server started, but the graphics are not displayed in the browser (tried different browsers, localhost:8080 and localhost:8080/example, with folder template name ) should be something very simple

**Comment by tobiasandersen** [comment]
There was a problem on windows machines. It should be fixed in the latest version ([caspar-graphics@1.0.0-beta.27](https://www.npmjs.com/package/@nxtedition/caspar-graphics/v/1.0.0-beta.27)).
