### ISSUE TITLE
Issues with running in development and building

### ISSUE THREAD

**Issue by Carolien-Heymans** [nxtedition/create-caspar-graphics#87]
Whenever I use npm run dev, I just get a green screen and nothing works :
![image](https://github.com/nxtedition/create-caspar-graphics/assets/58338097/16305ec6-403b-4377-a352-9fd81559e8d1)
I also am unable to build? 
![image](https://github.com/nxtedition/create-caspar-graphics/assets/58338097/39abb197-a5ea-443c-b865-0472b01b5cdd)
I tried running "npm run build" like the guide says but that does not work. "npm caspar-graphics build" also does nothing.

**Comment by Carolien-Heymans** [comment]
Hi, I tried this on a Mac and it works on that computer, so maybe it's a Windows issue?

**Comment by tobiasandersen** [comment]
This should be fixed in the latest version ([caspar-graphics@1.0.0-beta.27](https://www.npmjs.com/package/@nxtedition/caspar-graphics/v/1.0.0-beta.27)).
