### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#95]
Hello.

When I try to npm run dev I just get this:
![image](https://github.com/nxtedition/create-caspar-graphics/assets/89579091/b93c329b-9851-47ca-af75-844cbe0e5939)

I can se in the installation that there is some warnings...

Best regards Tue.

**Comment by 7u5a** [comment]
Before the `npm audit fix` when trying to run `npm run dev` it says:
Caspar Graphics v1.0.0-beta.30
after it says:
Caspar Graphics v1.0.0-y.0

**Comment by tobiasandersen** [comment]
`v1.0.0-beta.30` is the correct one. I don't think `npm audit fix` works well in this case because of the beta versions.

**Comment by tobiasandersen** [comment]
> So conclusion, do'nt run any npm audit fix unless it's not a beta?

Yes at least for this project. But I think we could publish a non-beta version and then hopefully the problem goes away.

> Where can I se the latest long term?

What do you mean?

> And by the way, where is the examples now?

Not sure I get this question either, could you elaborate?

**Comment by 7u5a** [comment]
> > So conclusion, do'nt run any npm audit fix unless it's not a beta?
> Yes at least for this project. But I think we could publish a non-beta version and then hopefully the problem goes away.
I'll will follow the publish

> > Where can I se the latest long term?
> What do you mean?
I mean, I can't see the versions anywhere and do you have a non-beta version from earlier?
 
> > And by the way, where is the examples now?
> Not sure I get this question either, could you elaborate?
Earlier when I installed, there was mor than one example, but not now, where have they gone?

**Comment by tobiasandersen** [comment]
I've published v1.0.0 now. You can see all version here: https://www.npmjs.com/package/@nxtedition/caspar-graphics?activeTab=versions. 

All examples are available here: https://github.com/nxtedition/create-caspar-graphics/tree/master/packages/examples/templates. But we don't clone them to your computer when you make a new project.
