### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#96]
When I use:
`npm create caspar-graphics@latest`

It' does not work as expected when I run the development server:
![image](https://github.com/nxtedition/create-caspar-graphics/assets/89579091/feee1d6d-326d-40c5-8779-aebaea3a1280)

But it's after af ran the:
`npm audit fix --force`

I did it because this:
`npm audit
# npm audit report
vite  5.0.0 - 5.0.12
Severity: high
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw    
Vite's `server.fs.deny` did not deny requests for patterns with directories. - https://github.com/advisories/GHSA-8jhw-289h-jh2g
fix available via `npm audit fix --force`
Will install @nxtedition/caspar-graphics@1.0.0-y.0, which is outside the stated dependency range
node_modules/vite
  @nxtedition/caspar-graphics  <=1.0.0-beta.30
  node_modules/@nxtedition/caspar-graphics

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix --force`

**Comment by tobiasandersen** [comment]
Is there any difference if you try creating a project with e.g. `npm create caspar-graphics@2.0.0-alpha.7` instead?

**Comment by 7u5a** [comment]
No, when using `npm create caspar-graphics@2.0.0-alpha.7` it's the same.
It happens when using the `npm audit fix` after the install
`added 175 packages, and audited 176 packages in 51s

  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.`

**Comment by tobiasandersen** [comment]
Replied here: https://github.com/nxtedition/create-caspar-graphics/issues/95#issuecomment-2099907557.
