### ISSUE TITLE
Question to “template”

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#97]
How is it possible to make a live clock?

**Comment by tobiasandersen** [comment]
We have a helper `useClock()` hook here: https://github.com/nxtedition/create-caspar-graphics/blob/master/packages/graphics-kit/src/use-clock.js. We haven't documented this one yet, but it can be used similar to the other hooks as described here: https://gfx.nxtedition.com/docs/hooks/use-image.

**Comment by 7u5a** [comment]
By the way, I've tryed to put an image in like this:
import React from 'react'
import { render, GsapTimeline, useCasparData } from '@nxtedition/graphics-kit'
import { useImage } from '@nxtedition/graphics-kit'
import './style.css'

const GsapImage = () => {
  const { image } = useImage({ src: './image.jpg' }) 

  return (
    <GsapTimeline
      /* hide={!image} */
    >
      <div key={image} id="image">
        <img src={image} />
      </div>
    </GsapTimeline>
  )
}

render(GsapImage)

But I can't get to work, what am I doing wrong?

**Comment by tobiasandersen** [comment]
It's close, but the options passed to it should be as described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat. 

This is probably what you want:

```jsx
const GsapUr = () => {
  const ur = useClock("da-DK", { hour: 'numeric', minute: 'numeric' })

  return (
    <GsapTimeline
      hide={!ur}
      onPlay={timeline => {
        timeline.from('#ur', { opacity: 0 })
      }}
      onStop={timeline => {
        timeline.to('#ur', { opacity: 0 })
      }}
    >
      <div id="ur">
        {ur}
      </div>
    </GsapTimeline>
  )
}
```
